import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "superdm-assingment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased flex items-center justify-center h-screen w-screen bg-[url(/images/bg.jpg)]`}>
        {children}
      </body>
    </html>
  );
}
